/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class forfun_tastendk_Foo */

#ifndef _Included_forfun_tastendk_Foo
#define _Included_forfun_tastendk_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     forfun_tastendk_Foo
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_forfun_tastendk_Foo_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
